### ISSUE TITLE
Sunset/Sunrise setting

### ISSUE THREAD

**Issue by jan-xyz** [ApolloZhu/Dynamic-Dark-Mode#15]
I really like the app! I think it would be really cool if the app used the same logic as the dynamic wallpapers to switch between day and night. The wallpaper uses azimuth and altitude to determine if the sun is above or below the horizon at your current location.

@mczachurski explains it very well in [his blog](https://itnext.io/macos-mojave-dynamic-wallpapers-ii-f8b1e55c82f) post for his [wallpaper tool](https://github.com/mczachurski/wallpapper).

**Comment by jan-xyz** [comment]
Nevermind I just found it in the settings but I get an error

<img width="532" alt="screenshot 2018-09-28 at 21 03 45" src="https://user-images.githubusercontent.com/5249233/46228369-2af96980-c362-11e8-82a5-1d5f682bf0c7.png">

**Comment by jan-xyz** [comment]
After closing and opening it a couple of times it started working. Now I can't get it to not work anymore. It's probably something that can be made a bit more robust and might be an initial setup problem.

**Comment by ApolloZhu** [comment]
Thanks for the feedback! I haven't got a chance to test the app yet, but I will check what's going on with the location processing code.

And yeah I don't think we need azimuth & attitude; sunset/sunrise time is good enough.

**Comment by jan-xyz** [comment]
Yeah, might be cool if it even stays in sync with the dynamic wallpaper. I imagine they can be a bit out of sync if they use different services, I'm not sure if it's possible to hook into it, especially considering that you want to stay away from private APIs.

**Comment by ApolloZhu** [comment]
@jan-xyz Do you mind testing out the new, 1.0.3 release? It should be alright except having error -1751 sometimes.

The new version has a setup process that asks for access to location, that should? solve the problem of not been able to access location when it first launches. You can re-run that process by using the re-setup button in the preferences pane, or you can check to see if you allowed Dynamic to access location through System Preferences.

> You may reset preferences for this app by running this in the terminal:
> `defaults delete io.github.apollozhu.Dynamic`

If it's still not working for you, please let me know (and possibly, with more details.)

**Comment by ApolloZhu** [comment]
Please reopen if you are still experiencing this issue.
