### ISSUE TITLE
Dynamic won't start

### ISSUE THREAD

**Issue by etrahretep** [ApolloZhu/Dynamic-Dark-Mode#16]
[Dynamic_2018-09-29-084255_Peters-iMac.txt](https://github.com/ApolloZhu/Dynamic-Dark-Mode/files/2430355/Dynamic_2018-09-29-084255_Peters-iMac.txt)

Downloaded and started; nothing happens.
system.log shows: com.apple.xpc.launchd[1] (io.github.apollozhu.Dynamic.58212[7716]): Service exited due to SIGABRT
Tried this on 3 machines.
In root it gives the message: Dynamic can't be started because it's damaged or missing components...

**Comment by etrahretep** [comment]
Solved it by starting the launcher inside the Dynamic package.
Strange.

**Comment by ApolloZhu** [comment]
Please re-download the latest release, the new zip file should contain a working version. 

I "accidentally" uploaded a wrongly packaged executable. (I really should check it before uploading, but I decided to trust Xcode's "Export" button in the notarization page.)

**Comment by ApolloZhu** [comment]
Do you mind moving the app into the Applications folder? That solved the problem for me.

**Comment by ApolloZhu** [comment]
Then I shall attribute this bug to Apple's buggy implementation of `UNUserNotificationCenter`.

It's their newer API that I'm supposed to use if I'd like to send out notifications (when an alert is too much), so I'll leave it to Apple to fix this.
