### ISSUE TITLE
Dynamic-Dark-Mode doesn't start at login

### ISSUE THREAD

**Issue by etrahretep** [ApolloZhu/Dynamic-Dark-Mode#20]
when clicking start at login nothing happens at restart/login
If I drag the launcher app manually to login items prefpane it works.

Repoducable on 2 computers

**Comment by ApolloZhu** [comment]
Is the app in the `/Applications` folder? Mine is working fine.

**Comment by etrahretep** [comment]
No, it is in /Users/peter/Applications. Can you explain why it should be in /Applications?
Permissions/automation?

**Comment by ApolloZhu** [comment]
I would say because most of the macOS APIs assume apps are present in the /Applications folder. Why? That's where they go if you install through the Mac App Store. I don't know what Apple's code look like, but my guess is that the "launch on login" list only keeps the name of the application. Later when they try to find the app, they look for it in the default path.

The settings pane is different. It's not sandboxed, therefore it has the privilege to read the fullpath of an application. That's probably why you don't have to put an app in a specific directory for it to work.

**Comment by etrahretep** [comment]
Thanks for explaining. Doesn't solve it though

**Comment by ApolloZhu** [comment]
Let me reset my launch items and give it a try. In the meanwhile could you please try to disable then enable it to see if that solves the problem?

**Comment by ApolloZhu** [comment]
So the latest release is working for me. It gets added to launch items immediately. 

You can confirm by checking the output of `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump | grep Dynamic`)

<details>
<summary>Sample Output</summary>

```diff
            CFBundleTypeName = "Dynamic Library";
		name:          Dynamic Library
            CFBundleTypeName = "Text-Based Dynamic Library Definition";
		name:          Text-Based Dynamic Library Definition
+++	path:          /Applications/Dynamic.app
	name:          Dynamic
	identifier:    io.github.apollozhu.Dynamic (0x80015909)
	executable:    Contents/MacOS/Dynamic
    CFBundleExecutable = Dynamic;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic";
    CFBundleName = Dynamic;
    NSAppleEventsUsageDescription = "This is how Dynamic Dark Mode manage the dark mode for you.";
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
    NSLocationUsageDescription = "This is how Dynamic Dark Mode calculates sunset/sunrise time.";
	library items: LoginItems/DynamicLauncher.app/
	activityTypes: pv-d4277e6601fa49, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic
+++	path:          /Applications/Dynamic.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80015916)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher
            CFBundleTypeName = "Text-Based Dynamic Library Definition";
		name:          Text-Based Dynamic Library Definition
        "com.apple.MobileAsset.MailDynamicData"
```
</details>

**Comment by etrahretep** [comment]
Hoe do i reset my launch items?

I did a grep and this is wat it outputs... (and there's nothing in trash)

Peters-MBP:~ peter$ /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump | grep Dynamic
    "com.apple.SystemConfiguration.SCDynamicStore-write-access" = 1;
	path:          /Users/peter/.Trash/Dynamic.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80009308)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher
	path:          /Users/peter/.Trash/Dynamic 20.20.09.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80009308)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher
	path:          /Applications/Adobe Photoshop CC 2018/Adobe Photoshop CC 2018.app/Contents/Required/DynamicLinkMediaServer/dynamiclinkmediaserver.app
	path:          /Volumes/Transport/Utilities/Dynamic.app
	name:          Dynamic
	identifier:    io.github.apollozhu.Dynamic (0x80009301)
	executable:    Contents/MacOS/Dynamic
    CFBundleExecutable = Dynamic;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic";
    CFBundleName = Dynamic;
    NSAppleEventsUsageDescription = "This is how Dynamic Dark Mode manage the dark mode for you.";
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
    NSLocationUsageDescription = "This is how Dynamic Dark Mode calculates sunset/sunrise time.";
	library items: LoginItems/DynamicLauncher.app/
	activityTypes: pv-d4277e6601fa49, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic
	path:          /Volumes/Transport/Utilities/Dynamic.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80009308)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher
        "com.apple.MobileAsset.MailDynamicData"
	path:          /Volumes/Peter's MacBook Pro Backup/Applications/Adobe Photoshop CC 2018/Adobe Photoshop CC 2018.app/Contents/Required/DynamicLinkMediaServer/dynamiclinkmediaserver.app
    NSHumanReadableCopyright = "Copyright \U00a9 2010-2016, App Dynamic. All rights reserved.";
	path:          /Volumes/Peter's MacBook Pro Backup/Applications/Adobe Lightroom Classic CC/Adobe Lightroom Classic CC.app/Contents/Helpers/DynamicLinkMediaServer/application/dynamiclinkmediaserver.app
	path:          /Applications/Adobe Lightroom Classic CC/Adobe Lightroom Classic CC.app/Contents/Helpers/DynamicLinkSupport/support/common/dynamiclink/dynamiclinkmanager.app
	path:          /Applications/Adobe Lightroom Classic CC/Adobe Lightroom Classic CC.app/Contents/Helpers/DynamicLinkMediaServer/application/dynamiclinkmediaserver.app
	path:          /Applications/Adobe Lightroom Classic CC/Adobe Lightroom Classic CC.app/Contents/Helpers/DynamicLinkMediaServer/application/dynamiclinkmediaserver.app/Contents/Adobe QT32 Server.app
            CFBundleTypeName = "Dynamic Library";
		name:          Dynamic Library
	path:          /Applications/Dynamic.app
	name:          Dynamic
	identifier:    io.github.apollozhu.Dynamic (0x80009301)
	executable:    Contents/MacOS/Dynamic
    CFBundleExecutable = Dynamic;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic";
    CFBundleName = Dynamic;
    NSAppleEventsUsageDescription = "This is how Dynamic Dark Mode manage the dark mode for you.";
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
    NSLocationUsageDescription = "This is how Dynamic Dark Mode calculates sunset/sunrise time.";
	library items: LoginItems/DynamicLauncher.app/
	activityTypes: pv-d4277e6601fa49, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic
	path:          /Applications/Dynamic.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80009308)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher
        "com.apple.MobileAsset.MailDynamicData"
    NSHumanReadableCopyright = "Copyright \U00a9 2010-2016, App Dynamic. All rights reserved.";
	path:          /Volumes/Transport/Utilities/Dynamic.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80009308)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher
	path:          /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/Peter's MBP/2018-10-03-183101/Peter's MBA/Users/peter/Desktop/Dynamic.app
	name:          Dynamic
	identifier:    io.github.apollozhu.Dynamic (0x80009301)
	executable:    Contents/MacOS/Dynamic
    CFBundleExecutable = Dynamic;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic";
    CFBundleName = Dynamic;
    NSAppleEventsUsageDescription = "This is how Dynamic Dark Mode manage the dark mode for you.";
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
    NSLocationUsageDescription = "This is how Dynamic Dark Mode calculates sunset/sunrise time.";
	library items: LoginItems/DynamicLauncher.app/
	activityTypes: pv-d4277e6601fa49, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic
	path:          /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/Peter's MBP/2018-10-03-183101/Peter's MBA/Users/peter/Desktop/Dynamic.app/Contents/Library/LoginItems/DynamicLauncher.app
	name:          DynamicLauncher
	identifier:    io.github.apollozhu.Dynamic.Launcher (0x80009308)
	executable:    Contents/MacOS/DynamicLauncher
    CFBundleExecutable = DynamicLauncher;
    CFBundleIdentifier = "io.github.apollozhu.Dynamic.Launcher";
    CFBundleName = DynamicLauncher;
    NSHumanReadableCopyright = "Copyright \U00a9 2018 Dynamic Dark Mode. All rights reserved.";
	activityTypes: pv-f07eeab5ab6cef, NOTIFICATION#KZ7D8X3PRK:io.github.apollozhu.Dynamic.Launcher

**Comment by ApolloZhu** [comment]
```
```

**Comment by robinmanuelthiel** [comment]
Same issue here. Can confirm that.

**Comment by ApolloZhu** [comment]
In the past 2 weeks, on my machines Dynamic Dark Mode always opens on start. If this is still happening to you, I don't really know what else we can do, but you can reopen the issue to add more inputs.
