### ISSUE TITLE
Add option to remove icon

### ISSUE THREAD

**Issue by Evertt** [ApolloZhu/Dynamic-Dark-Mode#26]
I've seen other apps do this. So the app runs completely invisible in the background and the way to get to the preferences window is to actually run the app again by opening it from Applications. And then also only while the preferences window is in front you can quit the app by pressing cmd+Q.

What do you think? I prefer to keep my screen as free from clutter as possible and especially apps like these are more of the kind "set it up and forget about it" so I wouldn't want them to have a presence on my screen.

**Comment by ApolloZhu** [comment]
Sounds reasonable. Will work on this when I have time.

**Comment by ApolloZhu** [comment]
@Evertt implemented in https://github.com/ApolloZhu/Dynamic-Dark-Mode/releases/tag/1.1.1
