### ISSUE TITLE
Homebrew Cask Support

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Dynamic-Dark-Mode#32]
I just realized that we only need 50 stars to be included. I’m thinking about using `dynamic-dark-mode` as the cask name.

**Comment by dgisser** [comment]
@ApolloZhu what do you want the Cask token to be? So they would type in cask install ____. Maybe dynamic-dark-mode is good?

**Comment by ApolloZhu** [comment]
Sounds good to me. @dgisser

**Comment by dgisser** [comment]
https://github.com/Homebrew/homebrew-cask/pull/54190

**Comment by vitorgalvao** [comment]
Cask tokens must adhere to [strict rules](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) to avoid duplicates. If you want the token to be `dynamic-dark-mode` you **must** rename the app bundle to `Dynamic Dark Mode`.

**Comment by ApolloZhu** [comment]
Thanks for letting us know! Will do so in the next release

**Comment by dgisser** [comment]
@ApolloZhu issue is ready to close
