### ISSUE TITLE
No app in Preferences -> Safe And Privacy -> Privacy -> Location Service

### ISSUE THREAD

**Issue by owenzhao** [ApolloZhu/Dynamic-Dark-Mode#34]
The app doesn't change to dark mode at the changing time.

So I look at if it really used the Location. There is no it in location privacy.

macOS Mojave 10.14.1 Beta (18B73a).

**Comment by ApolloZhu** [comment]
Not sure what happened, and never experienced this myself, but you can

1. Check if “Scheduled” option is checked
2. Use the “re setup” button in the app’s preferences window to try fixing this issue.

Either of those should fix this issue, if not, please let me know, possibly with more detailed information

**Comment by ApolloZhu** [comment]
If you are still experiencing this issue, please reopen and we can discuss about it.

**Comment by BasO** [comment]
This might be of use – after resetting SMC and PRAM, Dynamic Dark Mode finally asked permission to access System Events and Location.
