### ISSUE TITLE
Custom script execution

### ISSUE THREAD

**Issue by schrodincat** [ApolloZhu/Dynamic-Dark-Mode#37]
It would be useful to have ability to call custom script when transition happens in order to change theme in apps that don't (or cannot) mirror system settings.

Example: change Sublime Text, iTerm themes and color schemes

**Comment by ApolloZhu** [comment]
I think that behavior will be adopted by those app developers very soon (hopefully, and I think iTerm already have that feature?), but still, this can be an interesting addition

**Comment by ApolloZhu** [comment]
Hi @schrodincat ! I've given this feature some serious considerations, but eventually decide to not implement it. My main concern is security; I can't think of a way to validate the legitimacy of scripts the app will automatically execute. It's true that one can always go to check on the script(s), but generally the idea is that, when Dynamic Dark Mode is working as expected, its existence could be completely ignored. It's unfortunate that, as far as I known, Sublime Text doesn't have Mojave dark mode support yet, but a good news is iTerm has [this profile changing script](https://iterm2.com/python-api/examples/theme.html) in their official documentation.

I'm very sorry that I can't assist you further in your use case, and hope developers of the other apps will consider to support macOS Mojave Dark Mode soon in the future.
