### ISSUE TITLE
"Opens at Login" option doesn't work

### ISSUE THREAD

**Issue by schrodincat** [ApolloZhu/Dynamic-Dark-Mode#40]
App doesn't start automatically when this option checked

**Comment by ApolloZhu** [comment]
Is the app in the /Applications folder?

**Comment by schrodincat** [comment]
Yes, I’ve installed it through brew cask

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ApolloZhu** [comment]
What’s the output of this?

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump | grep Dynamic`

**Comment by ApolloZhu** [comment]
Hmmm... so it is in the login items but doesn’t open at login? I’ll try to see if anyone online has ever figured out why.

**Comment by schrodincat** [comment]
No, it's not in Login Items:
<img width="780" alt="screenshot 2018-11-02 at 18 30 22" src="https://user-images.githubusercontent.com/13354491/47924699-680acb80-decd-11e8-8b2c-dca873ab09da.png">

**Comment by koetsuji** [comment]
> No, it's not in Login Items:
> <img alt="screenshot 2018-11-02 at 18 30 22" width="780" src="https://user-images.githubusercontent.com/13354491/47924699-680acb80-decd-11e8-8b2c-dca873ab09da.png">

Try to add it manually on Login Items. Solved it for me.

**Comment by ApolloZhu** [comment]
@schrodincat Searching through [Open Radar](https://openradar.appspot.com/search?query=SMLoginItemSetEnabled), we can clear see that "open at login" usually won't work as expected. Even worse, [Apple is not interested in fixing their problems](https://openradar.appspot.com/10809456#ag9zfm9wZW5yYWRhci1ocmRyFAsSB0NvbW1lbnQYgICAwMj--QgM). I guess the workaround we have now is to manually adding this app to Login Items (like what @koetsuji did).
