### ISSUE TITLE
Location Service Unavailable - kCLErrorDomain error 0

### ISSUE THREAD

**Issue by SainteCelery** [ApolloZhu/Dynamic-Dark-Mode#41]
`The operation couldn’t be completed. (kCLErrorDomain error 0.)`

Same issue as referenced here:
https://github.com/ApolloZhu/Dynamic-Dark-Mode/issues/19
&
https://github.com/ApolloZhu/Dynamic-Dark-Mode/issues/15

Dynamic is selected in the Enable Location Services panel. Location Services are Enabled. System Services, Maps and Calendar have Location Services Enabled.

**Comment by ApolloZhu** [comment]
Based on [this StackOverflow answer](https://stackoverflow.com/questions/1409141/location-manager-error-kclerrordomain-error-0#1423719), macOS is unable to determine the current location from the current Wi-Fi connection. I'll probably add an option to enter the address/coordinate manually or something similar to solve this issue.

**Comment by ApolloZhu** [comment]
@SainteCelery please give 1.1.1 a try and see if it solves the problem
