### ISSUE TITLE
定时自动启动深色模式的小建议

### ISSUE THREAD

**Issue by Jreen** [ApolloZhu/Dynamic-Dark-Mode#45]
我遇到过定位服务 kclerrordomain 错误这样的错误 本来想发issue的，后来有老外回答Dynamic is selected in the Enable Location Services panel. Location Services are Enabled. System Services, Maps and Calendar have Location Services Enabled.

我建议在定时那块，最好有个解释，就是✓启用定位服务并启用该软件。

**Comment by ApolloZhu** [comment]
@Jreen 1.1.1 理论上来说对位置获取发生错误有了更好的处理，您可以尝试一下。

启用定位服务的引导其实之前已经有了（为了尝试通过苹果审核），点击设置里的“重新设置”按钮

![screen shot 2018-12-11 at 20 49 08](https://user-images.githubusercontent.com/10842684/49841664-6c58bd00-fd86-11e8-87a7-4d0fb4be3bc3.png)

跟着指示点下去就会显示这个界面

![screen shot 2018-12-11 at 20 40 11](https://user-images.githubusercontent.com/10842684/49841557-f6ecec80-fd85-11e8-9c37-c5f194b7cbe0.png)
