### ISSUE TITLE
dynamic mode based on brightness doesn't work latest macbook

### ISSUE THREAD

**Issue by idoo** [ApolloZhu/Dynamic-Dark-Mode#46]
Looks like something broken on latest MacBook with touch bar (maybe it's because the controller of brightness has been moved to T2 chip)

Do you have any ideas how to solve it?

**Comment by ApolloZhu** [comment]
If your Mac has an ambient light sensor, choose Apple menu > System Preferences, click Displays, then click Display, then select “Automatically adjust brightness.” Could you please try this first?

**Comment by idoo** [comment]
<img width="383" alt="built-in retina display 2018-12-08 14-35-19" src="https://user-images.githubusercontent.com/738921/49685576-7ebcc780-faf6-11e8-9667-e2bf3096e6c5.png">

it set by default

**Comment by ApolloZhu** [comment]
I actually experienced this myself today. Can you try to first disable then enable Auto Adjust within Dynamic Dark Mode and see if that works?

**Comment by idoo** [comment]
nope :( still the same result :(

**Comment by ApolloZhu** [comment]
https://github.com/ApolloZhu/Dynamic-Dark-Mode/blob/master/Dynamic/Utilities/Brightness/NSScreen%20%2B%20Brightness.swift handles that.

And there is a bug that when there are more than one displays, the program can’t determine the current brightness value.

**Comment by idoo** [comment]
so, it is based on display brightness, not light sensor, right?

**Comment by ApolloZhu** [comment]
Yes

On Dec 11, 2018, at 15:01, Ivan Verevkin <notifications@github.com<mailto:notifications@github.com>> wrote:


so, it is based on display brightness, not light sensor, right?

**Comment by idoo** [comment]
it makes sense, because as I understand there is no way to get value from the light sensor on macs with T1 and T2 chips, because it used private API that doesn't works anymore (it still works well on mac without touchbar btw)

**Comment by ApolloZhu** [comment]
Okay....

I’ll try to find a Mac that I can test on and see if there’s a way to solve this problem

**Comment by idoo** [comment]
let me know if I can help you somehow, I have a mac with T2 chip

https://stackoverflow.com/a/18614019
there was a way to read such data from an Ambilight sensor (you still can use it for old MacBooks), but there are not `AppleLMUController` anymore ¯\_(ツ)_/¯

So, I'll appreciate if you can find some way to read it

**Comment by ApolloZhu** [comment]
I don't think https://github.com/ApolloZhu/Dynamic-Dark-Mode/releases/tag/1.1.1 helps much, but it did solve the problem for me myself. Can you try this new version and see what happens?

**Comment by ApolloZhu** [comment]
@idoo I just tested the 1.1.1 release on my friend's new MacBook Pro 2018 with touch bar and it works perfectly. You should try it out and see if it works or not. Or you can describe your situation in more details so I may find out what other things could have caused the problem.

**Comment by idoo** [comment]
sorry, didn't respond, yes, it works perfectly now! thanks!
