### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Dynamic-Dark-Mode#48]
- [ ] SMLoginItemSetEnabled
- [ ] AEDeterminePermissionToAutomateTarget

Most likely Apple used [`dispatch_semaphore_create`](https://developer.apple.com/documentation/dispatch/1452955-dispatch_semaphore_create) but forgot to [`dispatch_release`](https://developer.apple.com/documentation/dispatch/1496328-dispatch_release). Filed a bug report (problemID=46718931) and we'll see how this goes.

**Comment by CaptainYukinoshitaHachiman** [comment]
It doesn't make sense to leave the Big Report ID here since the reports are only visible to the submitter and Apple.

**Comment by ApolloZhu** [comment]
It’s for (friends of) Apple engineers who see this issue by chance and hopefully expedite solving it.

**Comment by ApolloZhu** [comment]
Another one: https://github.com/jianstm/Schedule/issues/31
