### ISSUE TITLE
App 无法启动

### ISSUE THREAD

**Issue by mpco** [ApolloZhu/Dynamic-Dark-Mode#49]
OS: 10.14.2

下载 zip 解压后，打开就 crash，看不到图标界面之类的

Crash 报告：[Dynamic Dark Mode_2018-12-14-230917.zip](https://github.com/ApolloZhu/Dynamic-Dark-Mode/files/2682647/Dynamic.Dark.Mode_2018-12-14-230917.zip)

**Comment by ApolloZhu** [comment]
请将应用移动到 /Applications 文件夹中
