### ISSUE TITLE
Inconsistent version number

### ISSUE THREAD

**Issue by core-code** [ApolloZhu/Dynamic-Dark-Mode#56]
i've downloaded Version '1.1.3' (both the ZIP and the PKG) but when selecting it in the Finder and using 'QuickLook' it shows Version '1.1'

you have forgot to update the CFBundleShortVersionString and CFBundleVersion entries in the Info.plist

<img width="863" alt="screenshot 2019-02-18 at 12 29 51" src="https://user-images.githubusercontent.com/1261954/52948170-0cc7f080-3379-11e9-99c8-4b2b092ba673.png">

**Comment by core-code** [comment]
additionally the CFBundleVersion for the 1.1 release has been lower for the 1.1 release than for previous releases. the CFBundleVersion value should increase for each new release as per Apple's rules. for Apps distributed on the Mac App Store this rule is even enforced technically.

this should fix it:

```
	<key>CFBundleShortVersionString</key>
	<string>1.1.3</string>
	<key>CFBundleVersion</key>
	<string>1.1.3</string>
```

**Comment by ApolloZhu** [comment]
Technically the current version 1.1 (3) but I’ll switch to the other style.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by andrewmincn** [comment]
why can't down

**Comment by ApolloZhu** [comment]
@andrewmincn install via Homebrew (https://brew.sh/) using this command:
```
brew cask install dynamic-dark-mode
```
 or download the pkg/zip file from this page: https://github.com/ApolloZhu/Dynamic-Dark-Mode/releases/latest
