### ISSUE TITLE
Report Bug Message After Every Screen Wakeup

### ISSUE THREAD

**Issue by Kosezu** [ApolloZhu/Dynamic-Dark-Mode#59]
This is my first time submitting an error report, so apologies.

I get the following error every time my screen sleeps and I come back to wake it up: 

**Report Error To Developer**
nil: estimatedNextExecution

How can I get this resolved?

**Comment by ApolloZhu** [comment]
Thank you very much for sharing this. Could you please share with me:

0. Is scheduled dark mode enabled?

If so, then:

1. Is scheduled dark mode working?
2. What’s the current shown in preferences page?
3. Have this happened on any other day?
4. Any other information that you’d like to share

If you don’t want to see this error before I’m able to fix it, you can turn off scheduled dark mode temporarily.

**Comment by Kosezu** [comment]
0. Enables, for Official Sunset Sunrise

1. I just started using the app yesterday, but it turned on dark mode correctly last night, this morning, it did not turn dark mode off at the scheduled time. Possible because the Mac was asleep.

2. Preference Page: Shortcut is default. Auto Adjust is off. Scheduled is Official Sunset Sunrise. Menu Bar Item is Hidden. Other is checked for Opens At Login.

3. I have only used the app one day/night. This is the second day now, so I will check and see if it works properly tonight. 

4. Love the app so far. Minimal and does what needs to be done! 
Also, I downloaded the app as a Direct Download, not through Homebrew.

**Comment by ApolloZhu** [comment]
<details>
<summary>I had and only had this problem on March 20, 2019 at 01:08 EDT...</summary>

![nil estimate](https://user-images.githubusercontent.com/10842684/55272759-de9ed000-5297-11e9-9b6b-c7940efe3c29.png)

</details>

I'll modify the alert message and see if this ever happens again

**Comment by ApolloZhu** [comment]
According to https://github.com/jianstm/Schedule/issues/30, this issue has been fixed. We'll see if that is the case.
