### ISSUE TITLE
when auto switch triggered, the AmbientDisplayAgent process  use cpu a lot.

### ISSUE THREAD

**Issue by wee911** [ApolloZhu/Dynamic-Dark-Mode#61]
when auto switch triggered, the AmbientDisplayAgent process  use cpu a lot. and i use external 
monitor

**Comment by ApolloZhu** [comment]
This is a known bug for macOS. Please contact Apple Support/Apple Bug Report and hope they’ll solve this issue soon (which existed since Sierra, possibly even earlier).
