### ISSUE TITLE
当系统时间更新时会导致窗口失去焦点

### ISSUE THREAD

**Issue by xfzka** [ApolloZhu/Dynamic-Dark-Mode#62]
当执行 `sudo sntp -sS time.asia.apple.com`更新系统时间后，或系统自动更新时间后，窗口焦点会切换到`Dynamic-Dark-Mode`上，这很影响体验，比如在聊天、写代码、编辑视频或者照片，都很影响体验。

希望能进行下处理。

**Comment by ApolloZhu** [comment]
确实有这个问题，正在研究如何改进 Apple Script 来返回焦点

> 注：准确的说是会切换到 System Events 上，之前测试过程中 Dynamic Dark Mode 也失去了焦点，一直没人抱怨所以没花太多时间处理。谢谢反馈。

**Comment by ApolloZhu** [comment]
问题的解决方案是有的，但是需要关闭沙盒。因为这是一个重要的决定，请先让我考虑考虑，谢谢
