### ISSUE TITLE
根据屏幕亮度自动切换相关

### ISSUE THREAD

**Issue by ppttvs** [ApolloZhu/Dynamic-Dark-Mode#65]
勾选了根据屏幕亮度自动切换，但是屏幕亮度由于环境光的变化而变化的时候，即使超过了设置的阈值也不会自动切换，必须手动按一下亮度调节按钮才会切换。
系统版本 Mojave 10.14.4 (18E226)
MacBook Pro (15-inch, 2017)
[问题复现视频.zip](https://github.com/ApolloZhu/Dynamic-Dark-Mode/files/3160248/default.zip)

**Comment by ApolloZhu** [comment]
确实，我尽快研究研究苹果在底层做了什么更改

**Comment by FengweiHu** [comment]
你好，能否介绍一下阀值大小的含义？阀值越大，表示需要更大的亮度才能自动切换到深色模式吗？另外，这一项是否会受到屏幕色温的影响？比如同时安装了f.lux @ApolloZhu

**Comment by ApolloZhu** [comment]
@FengweiHu 

圆点左边是深色模式，右边是浅色模式。下一个版本将会改成这样：

![image](https://user-images.githubusercontent.com/10842684/57988035-43d09f80-7a57-11e9-932c-85a0f0466ff6.png)

亮度是直接读取屏幕的亮度，个人觉得色温没啥影响？您可以实际尝试一下来选择合适的阀值

**Comment by owenzhao** [comment]
遇到了同样的问题。只有用鼠标或者键盘改亮度的时候，才会切换。或者是解锁的时候才能自动运行。

环境光线改变系统自动调节的时候，不会切换。

**Comment by HsiangHo** [comment]
已在10.14.4上测试通过 @ApolloZhu

**Comment by owenzhao** [comment]
我用的是brew版，能否更新一下这个新版？

**Comment by ApolloZhu** [comment]
@owenzhao 已更新
