### ISSUE TITLE
感谢提供实用的自动转换功能，建议将其他应用软件的转换也纳入管理。

### ISSUE THREAD

**Issue by bawfnje** [ApolloZhu/Dynamic-Dark-Mode#66]
例如开发常用的Intellij Idea，Atom等，本身都自带有切换，如果能像系统的黑暗模式一样纳入管理就完美了，再次感谢！

**Comment by ApolloZhu** [comment]
Atom: https://atom.io/packages/mojave-dark-mode
IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-203554

如在 #37 里提到的，暂时不会增加对第三方软件的特殊支持，请考虑向这些应用程序的开发者提出反馈（比如 IntelliJ）来促使它们完成这项功能，或者安装已有的插件（比如 Atom）来实现。

目前来看有可能以后（比如 6 月 3 日苹果开发者大会之后）我会考虑加入一个插件系统来支持第三方软件，但目前来说我还是衷心希望所有的开发者都能尽快支持 macOS Mojave 的深色模式。对此给您带来的不便还望谅解，谢谢。
